# zmodload zsh/zprof

setopt clobber

# Source Zgen and create init file if necessary
# Add custom Zsh plugins to .zgen-setup.zsh
source ~/.zgen-setup.zsh

# Add customizations below
export ENABLE_DOCKER_PROMPT=true
export LAZY_NODE_PROMPT=true
export VISUAL=idea
export GOPATH="$HOME/golang"
export PROJECTS_DIR="$HOME/code"

alias e.="${VISUAL:-vi} ."
alias e.rc="$VISUAL ~/dotfiles"
alias cd.rc="cd ~/dotfiles"
alias git=hub
alias .rc="source ~/.zshrc"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="/usr/local/bin:$GOPATH/bin:$HOME/.rvm/bin:$PATH"

alias dog='pygmentize -g'

[[ -f $HOME/.sdkman/var/candidates ]] && rm -f $HOME/.sdkman/var/candidates
[[ -f $HOME/.sdkman/var/version ]] && rm -f $HOME/.sdkman/var/version
[[ -f $HOME/.sdkman/bin/sdkman-init.sh ]] && source "$HOME/.sdkman/bin/sdkman-init.sh" || true

# zprof
