RAD_DOTFILES_PROFILE=home

# Detect and set DOTFILES_DIR
for d in "$HOME/icode/dotfiles" "$HOME/code/dotfiles" "$HOME/projects/dotfiles"; do
  [[ -d $d ]] && { DOTFILES_DIR=$d; break; }
done

(
  rad-realpath() { [ -d "$1" ] && cd "$1" 2>/dev/null && pwd || { cd "$(dirname "$1")" 2>/dev/null && echo "$(pwd)/$(basename "$1")"; }; }
  RAD_ZSHRC_PATH="$(print -r -- "${(%):-%x}")"
  DOTFILES_ZSHRC_PATH="$(rad-realpath "${(%):-%x}")"
  if [[ "${RAD_ZSHRC_PATH}" == "${DOTFILES_ZSHRC_PATH}" ]]; then
    cd $DOTFILES_DIR
    ls -la
    ./install_dotfiles.sh "${RAD_DOTFILES_PROFILE}"
  fi
)

source ~/.zshrc_global

colormap() {
  for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
}

alias ls=lsd
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
#
# zstyle ':autocomplete:*' min-input 3
# zstyle ':autocomplete:*' delay 2
#
# # all Tab widgets
# zstyle ':autocomplete:*complete*:*' insert-unambiguous yes
#
# # all history widgets
# zstyle ':autocomplete:*history*:*' insert-unambiguous yes
#
# # ^S
# zstyle ':autocomplete:menu-search:*' insert-unambiguous yes

# bindkey              '^I' menu-select
# bindkey "$terminfo[kcbt]" menu-select

# bindkey -M menuselect              '^I'         menu-complete
# bindkey -M menuselect "$terminfo[kcbt]" reverse-menu-complete

alias l=nav
#
# bindkey -M emacs \
#     "^[p"   .history-search-backward \
#     "^[n"   .history-search-forward \
#     "^P"    .up-line-or-history \
#     "^[OA"  .up-line-or-history \
#     "^[[A"  .up-line-or-history \
#     "^N"    .down-line-or-history \
#     "^[OB"  .down-line-or-history \
#     "^[[B"  .down-line-or-history \
#     "^R"    .history-incremental-search-backward \
#     "^S"    .history-incremental-search-forward \
#     #
# bindkey -a \
#     "^P"    .up-history \
#     "^N"    .down-history \
#     "k"     .up-line-or-history \
#     "^[OA"  .up-line-or-history \
#     "^[[A"  .up-line-or-history \
#     "j"     .down-line-or-history \
#     "^[OB"  .down-line-or-history \
#     "^[[B"  .down-line-or-history \
#     "/"     .vi-history-search-backward \
#     "?"     .vi-history-search-forward \
#     #
#

#
# bindkey '^I'   complete-word       # tab          | complete
# bindkey '^[[Z' autosuggest-accept  # shift + tab  | autosuggest
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/brandonfryslie/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
