# .zshrc file for development use at work

# zmodload zsh/zprof
setopt clobber
setopt share_history

# Set path...dunno why this changed
export PATH="$PATH:/usr/local/bin"

# Source Zgen and create init file if necessary
# Add custom Zsh plugins to .zgen-setup.zsh
source ~/.rad-shell/rad-init.zsh

# Add customizations below

# Theme configuration
# export ENABLE_DOCKER_PROMPT=true
export LAZY_NODE_PROMPT=true

# Editor configuration
export VISUAL=idea
export EDITOR=vi

# Local code configuration
export PROJECTS_DIR="$HOME/code"
export DOTFILES_DIR="$HOME/code/dotfiles"

# Language configuration

# Github configuration
export GHE_USERNAME=brandon-fryslie

# ---

# Misc
alias e.="${VISUAL:-vi} ."
alias dog='pygmentize -g'
git config --global core.excludesfile ~/.gitignore_global

AUTO_MENU=true
AUTO_LIST=true
#unsetopt listambiguous
setopt AUTO_MENU
setopt AUTO_LIST
setopt GLOB_COMPLETE
setopt COMPLETE_ALIASES
setopt AUTO_PARAM_SLASH

export LPASS_AGENT_TIMEOUT="28800"

export OKTA2AWS_DUO_MFA_OPTION='Passcode'

jcd() {
  jc-cli --dev $HOME/code/jc-cli-py "$@"
}

# Completion engine
# completion init...shouldn't this be loaded already?
autoload -Uz compinit
compinit
[[ -f $HOME/.jfrog/jfrog_zsh_completion ]] && source $HOME/.jfrog/jfrog_zsh_completion

autoload -U +X bashcompinit && bashcompinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# / Completion engine

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# / Pyenv

# Terraform
complete -o nospace -C /usr/local/Cellar/tfenv/2.2.2/versions/0.15.3/terraform terraform

#export PATH="$HOME/code/terraform-docker/bin:$PATH"
# / Terraform

# GoLang

export GOROOT=/usr/local/go
export GOPATH=$HOME/go-global
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# / GoLang

#export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_151`

#export PATH="/usr/local/opt/ansible@2.9/bin:$PATH"

export PATH="$PATH:$HOME/code/ml-handy-scripts/bin"

eval "$(rbenv init -)"

export PATH="$PATH:$HOME/code/mlde-cloud-deploy/bin"


# / MLDevOps
[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)

export ENABLE_SCYLLA_PROMPT=true

