#!/usr/bin/env bash
# Converge the agent code-review GitHub Action in the current repo onto the
# desired config: render the desired state first (pure), diff it against what
# is deployed, and perform only the effects the diff demands. Re-running when
# everything is current is a fast no-op that needs no keychain.
# [LAW:effects-at-boundaries] compute the description, act only at the edge.
#
# Two independent convergence targets:
#   1. .github/workflows/code-review.yml matches the embedded template.
#   2. Every secret in SECRETS is set on the repo (re-synced from the macOS
#      keychain whenever the keychain is reachable, so rotation propagates).
#
# Each secret flows keychain -> gh over a pipe. It is never bound to a variable,
# never passed in argv, never printed. [LAW:effects-at-boundaries]
#
# Committing/pushing the workflow is intentionally NOT done here — that is a git
# policy decision (branch vs. default, PR) left to the caller. [LAW:decomposition]
set -euo pipefail

# Pinned to a commit SHA, not the moving `v1` tag. The workflow hands this action
# CLAUDE_CODE_OAUTH_TOKEN and DEEPSEEK_API_KEY and relies on its fork gating, so a
# moved or force-pushed tag — or a compromised account — would change what runs with
# every consuming repo's secrets in scope, with no diff in any of them to show it.
# A SHA cannot be moved. The subscription token STRENGTHENS this argument rather than
# weakening it: it is a long-lived OAuth credential with a far larger blast radius
# than a per-service API key, so what receives it must never change silently.
#
# The pin is also why the 1.42.0 `auto` retarget did not break repos installed by this
# script while it broke every repo pinned to `@v1`: a SHA-pinned repo keeps running the
# build it was installed with until this line moves. That is the pin working as designed.
#
# [LAW:one-source-of-truth] This line is where "what is current" is decided; to
# bump, resolve the tag and update the SHA and the trailing comment together:
#   gh api repos/promptctl/copirate-code-review-agent/git/ref/tags/v1 --jq .object.sha
ACTION_REF="promptctl/copirate-code-review-agent@669c4ea7b3b2a4d7c3bc88a96c73a42302ebe046"  # v1 = 1.43.0
# [LAW:one-type-per-behavior] The secrets differ only in their name and in which env
# var overrides their keychain item. Everything else about provisioning them — the
# emptiness gate, the Actions+Dependabot double-set, the three reachability cases — is
# identical, so these are two INSTANCES of one convergence, never two copies of it.
# A third secret is one more line here and no new code. Each entry is
# "<secret name>|<keychain-item override env var>"; the keychain item defaults to the
# secret's own name, so there is no second literal to drift. [LAW:one-source-of-truth]
#
# CLAUDE_CODE_OAUTH_TOKEN is a Claude Pro/Max subscription token from `claude
# setup-token`, which the action reads once subscription auth ships (lit
# zai-billing-xl0.1). Distributing it per-repo through this installer is the deliberate
# alternative to an org-wide secret — org secrets reach only repos in that org, while
# this reaches every repo the installer touches. Listing it here makes it REQUIRED like
# any other entry: an install that cannot provision it stops rather than half-succeeding.
SECRETS=(
  "DEEPSEEK_API_KEY|DEEPSEEK_KEYCHAIN_ITEM"
  "CLAUDE_CODE_OAUTH_TOKEN|CLAUDE_CODE_OAUTH_KEYCHAIN_ITEM"
)
WORKFLOW_PATH=".github/workflows/code-review.yml"

die() { echo "ERROR: $*" >&2; exit 1; }

# --- Preconditions both targets need. Each fails loudly with a specific
# cause; the keychain is deliberately NOT here — it is an input to exactly one
# effect and is demanded only when that effect must write. [LAW:no-silent-failure]

command -v gh >/dev/null 2>&1 || die "GitHub CLI 'gh' is not installed (https://cli.github.com)."

git rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || die "not inside a git repository (cwd=$PWD)."

gh auth status >/dev/null 2>&1 \
  || die "gh is not authenticated. Run: gh auth login"

# Resolves the repo from the current dir's remote AND confirms gh can reach it.
REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null)" \
  || die "gh could not resolve a GitHub repo for $PWD (no GitHub remote, or no access)."

# --- Desired state: render the workflow. Pure — no writes into the repo yet. ---
# Quoted heredoc: GitHub Actions \${{ ... }} expressions pass through literally.
DESIRED="$(mktemp)"
trap 'rm -f "$DESIRED"' EXIT
cat > "$DESIRED" <<'YAML'
# GENERATED by agent-code-review-setup/install.sh — do not edit by hand.
# This file is a derived copy of the template embedded in install.sh; the
# installer reconverges it on every run and will overwrite local edits.
# To change the workflow, change the template and re-run the installer.
name: AI Code Review

# pull_request (unprivileged), NOT pull_request_target: this job checks out the
# PR head. Under pull_request_target that checkout runs privileged, with secrets
# in scope — the untrusted-checkout pattern CodeQL flags as high and that nothing
# structurally disproves (a later step could execute the checked-out tree).
# pull_request keeps the run unprivileged, so that risk cannot arise.
#
# Dependabot PRs and the secret store — LOAD-BEARING: GitHub withholds *Actions*
# secrets from Dependabot-triggered runs and instead populates the `secrets.*`
# context from a SEPARATE store (repo Settings → Secrets → Dependabot). So
# `${{ secrets.DEEPSEEK_API_KEY }}` below resolves from the Actions store for a
# human PR and from the Dependabot store for dependabot[bot]. The key MUST exist
# in BOTH stores or Dependabot reviews silently get an empty key — install.sh
# sets both. The GITHUB_TOKEN is read-only by default on Dependabot runs; the
# permissions block below elevates it so the reviewer can post its comments.
# External fork PRs get no secrets and are gated out by the action's own
# prIsFromFork check.
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

# One review at a time per PR: a new push supersedes the in-flight review of
# the old SHA rather than racing it to post comments.
concurrency:
  group: code-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    # Cap a hung review (network stall, API retry loop) instead of letting it hold
    # a runner for GitHub's 6-hour default. Reviews finish in ~2-4 min typically,
    # but API congestion has stretched successful runs to 11-15 min (observed
    # 2026-08: two runs were killed at a 15-min cap and passed on rerun), so the
    # cap sits well above that tail.
    timeout-minutes: 30
    steps:
      - name: Checkout pull request
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Pinned by SHA rather than by tag, and deliberately so: this step receives a
      # long-lived subscription token, and a tag can be moved under it without any diff
      # landing in this repo. The SHA is chosen in install.sh, which owns this file.
      #
      # BOTH credentials are passed on purpose. PROVIDER defaults to `auto`, which the
      # action retargets centrally — it moved from deepseek to claude-subscription in
      # 1.42.0 — and a workflow carrying only the then-current target's secret breaks the
      # day it moves. Passing both means a retarget needs no edit here: PROVIDER alone
      # selects the provider and credential presence never steers it, so the unused input
      # is simply never read. The action fails loudly, before spending anything, if the
      # credential for the CURRENT target is the one missing.
      - name: Code Review
        uses: __ACTION_REF__
        with:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          # DEPENDENCY_DIFF is on for EVERY repo this installs into — a deliberate
          # universal default baked into the template, NOT a per-repo divergence that
          # leaked in. On a PR that bumps a dependency the reviewer fetches the bumped
          # module's upstream commits and changed files instead of reviewing a bare
          # version string; that context helps in any repo and costs only a little
          # review time. Because it lives in the template, this IS the baseline: a
          # re-run of the installer preserves it. Do not "reconverge to a barer
          # default" by removing it — there is no barer default, and stripping it
          # silently degrades every dependency-bump review.
          DEPENDENCY_DIFF: "true"
YAML
# Insert the pinned ref without escaping every GH expression in the heredoc.
grep -q '__ACTION_REF__' "$DESIRED" || die "workflow template lost its action-ref marker."
TMP="$(mktemp)"
trap 'rm -f "$DESIRED" "$TMP"' EXIT
sed "s|__ACTION_REF__|${ACTION_REF}|" "$DESIRED" > "$TMP" && mv "$TMP" "$DESIRED"

# --- Effect 1: converge the workflow file. An absent deployed file is a real
# domain value (fresh install), handled explicitly, not an error to suppress.
#
# But one repo must NOT be converged onto the consumer template: the action's
# own source repo, whose workflow deliberately dogfoods the LOCAL action via
# `uses: ./` (with PROVIDER: auto, the dist/** exclusion, transcript archival).
# Rewriting it to `uses: __ACTION_REF__` would destroy that dogfooding config on
# every review-loop preflight. We recognize that repo by the one marker only it
# carries — a `uses:` step pointing at a local action path (`./…`), the very
# thing that MAKES it a dogfood workflow — read straight from the deployed file
# rather than matched against a repo name, which has already drifted from
# ACTION_REF's owner/name and cannot be trusted. [LAW:one-source-of-truth]
# The deployed `uses: ./` IS the territory; we read it, we don't re-derive it.
if [ -f "$WORKFLOW_PATH" ] && grep -Eq '^[[:space:]]*uses:[[:space:]]*\./' "$WORKFLOW_PATH"; then
  WORKFLOW_CHANGED=0
  echo "✓ $WORKFLOW_PATH references a local action (uses: ./) — this is the action's own"
  echo "  source repo dogfooding itself; leaving its workflow untouched (not a consumer to converge)."
elif [ -f "$WORKFLOW_PATH" ] && cmp -s "$DESIRED" "$WORKFLOW_PATH"; then
  WORKFLOW_CHANGED=0
  echo "✓ $WORKFLOW_PATH is up to date (uses $ACTION_REF)"
else
  WORKFLOW_CHANGED=1
  mkdir -p "$(dirname "$WORKFLOW_PATH")"
  cp "$DESIRED" "$WORKFLOW_PATH"
  echo "✓ wrote $WORKFLOW_PATH (uses $ACTION_REF)"
fi

# --- Effect 2: converge each secret. The keychain is canonical and the repo
# secret is its derived copy [LAW:one-source-of-truth]: reachable keychain →
# re-sync (rotation propagates); unreachable keychain + existing copy → the
# observable desired state holds, warn that re-sync is impossible from this
# machine; unreachable keychain + no copy → fail loudly, because the reviewer
# cannot authenticate and a later "clean review" would be a lie.
# [LAW:no-silent-failure]
keychain_has_item() {
  command -v security >/dev/null 2>&1 \
    && security find-generic-password -s "$1" >/dev/null 2>&1
}
secret_on_repo() {
  # A failed listing must not read as "secret absent" — that would route a gh
  # outage into the fatal missing-secret verdict with a message naming the
  # wrong cause. List first, fail distinctly. [LAW:no-silent-failure]
  local names
  names="$(gh secret list --json name -q '.[].name')" \
    || die "could not list repo secrets on $REPO — cannot tell whether $1 is set; fix gh access and re-run."
  grep -qxF "$1" <<<"$names"
}
converge_secret() {
  local secret_name="$1" override_var="$2"
  # Keychain item shares the secret's name by default: one canonical name, no second
  # literal to drift out of sync. [LAW:one-source-of-truth]
  local keychain_item="${!override_var:-$secret_name}"

  if keychain_has_item "$keychain_item"; then
    # A keychain item can hold an empty value and still read back exit 0 —
    # pipefail only guards nonzero exits — and an empty value here would set an
    # empty repo secret that breaks the reviewer silently at review time.
    # Validate at the trust boundary via byte count so the value itself never
    # touches a shell variable. [LAW:no-silent-failure]
    [ "$(security find-generic-password -s "$keychain_item" -w | tr -d '\n' | wc -c)" -gt 0 ] \
      || die "keychain item '$keychain_item' has an empty value — refusing to set an empty $secret_name."
    echo "→ syncing secret $secret_name on $REPO (Actions + Dependabot) from keychain item '$keychain_item'…"
    # Both stores are required: Dependabot-triggered runs read secrets from a
    # SEPARATE store from Actions, so an Actions-only secret leaves every Dependabot
    # PR review unauthenticated (the reviewer's whole reason to exist on dep bumps).
    # [LAW:one-source-of-truth] keychain is canonical; both stores are derived copies.
    # pipefail aborts the pipeline on a failed 'security' read; the emptiness gate
    # above covers the successful-but-empty read. tr strips security's trailing
    # newline. The value is piped straight to gh and never touches a shell variable,
    # so we read the keychain once per store rather than caching it.
    security find-generic-password -s "$keychain_item" -w | tr -d '\n' | gh secret set "$secret_name"
    security find-generic-password -s "$keychain_item" -w | tr -d '\n' | gh secret set "$secret_name" --app dependabot
    echo "✓ set secret $secret_name on $REPO (Actions + Dependabot)"
  elif secret_on_repo "$secret_name"; then
    {
      echo "! secret $secret_name exists on $REPO but keychain item '$keychain_item' is not on this machine,"
      echo "  so it cannot be re-synced from here; the existing repo secret is left as-is."
      echo "  To re-enable syncing: add the keychain item, or point $override_var at the right one."
    } >&2
  else
    # Every secret in SECRETS is required, unconditionally. There is deliberately no
    # lenient arm for "the workflow does not reference it yet" — that would let a repo
    # finish the install believing it was provisioned when it was not, and the gap would
    # surface later as an unauthenticated review with nothing pointing back here. If a
    # secret is listed, it gets provisioned or the install stops. [LAW:no-silent-failure]
    die "secret $secret_name is not set on $REPO and keychain item '$keychain_item' is not available to set it — the reviewer cannot authenticate. Add the keychain item (or set $override_var) and re-run."
  fi
}

# [LAW:dataflow-not-control-flow] Same operation over every secret; which secrets exist
# is data, not structure. "A|B" splits on the single delimiter the table declares.
for secret_entry in "${SECRETS[@]}"; do
  converge_secret "${secret_entry%%|*}" "${secret_entry##*|}"
done

if [ "$WORKFLOW_CHANGED" -eq 1 ]; then
  cat <<EOF

Workflow file changed. Next step (left to you, per your git workflow):
  git add $WORKFLOW_PATH
  git commit -m "Install agent code review action"
  git push    # the workflow runs on PRs once it lands on the default branch
EOF
fi
