# Uncomment to enable profiling
# zmodload zsh/zprof

setopt clobber
setopt share_history

# Source Zgen and create init file if necessary
# Add custom Zsh plugins to .zgen-setup.zsh
source ~/.rad-shell/rad-init.zsh

# Add customizations below

# Theme configuration
export ENABLE_DOCKER_PROMPT=true
export LAZY_NODE_PROMPT=true

# Editor configuration
export VISUAL=idea
export EDITOR=vi

# Local code configuration
export PROJECTS_DIR="$HOME/code"
export DOTFILES_DIR="$HOME/code/dotfiles"

# Language configuration


# Ruby
#export PATH="$HOME/.rvm/bin:$PATH"

# Python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Github configuration
export GHE_USERNAME=brandon-fryslie

# ---

# Misc
alias e.="${VISUAL:-vi} ."
alias dog='pygmentize -g'
git config --global core.excludesfile ~/.gitignore_global

# Move to a rad-shell plugin
# Try finding the first ethernet adapter that has a valid ipv4 address
local-ip() {
  for i in `seq 0 10`; do
    res="$(/sbin/ifconfig en${i} | grep 'inet' | grep -v inet6 | awk '{print $2}')"
    [[ -n $res ]] && echo $res && return
  done
}

AUTO_MENU=true
AUTO_LIST=true
#unsetopt listambiguous
setopt AUTO_MENU
setopt AUTO_LIST
setopt GLOB_COMPLETE
setopt COMPLETE_ALIASES
setopt AUTO_PARAM_SLASH

drone-helper() {
  for i in `seq 86 99 && seq 130 144 | egrep -v '85|130'`; do
    dhost $i
    eval "$1 2>&1 &"
  done
}

# For profiling shell startup time
# zprof

# should tab complete to allow picing a sub folder of this dir
# /Users/brandon.fryslie/.zgen
zgen-edit() {
  true
}

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_151`
alias ap="~/code/workstation/docker-ansible/bin/docker-ansible-playbook -u brandon.fryslie"

# Uncomment to enable profiling
# zprof
