# Modular Powerlevel10k Configuration
#
# Generated by Powerlevel10k configuration wizard on 2025-07-21 at 00:46 MDT.
# Based on romkatv/powerlevel10k/config/p10k-classic.zsh, checksum 13396.
# Wizard options: nerdfont-v3 + powerline, small icons, classic, unicode, dark,
# 24h time, angled separators, sharp heads, flat tails, 2 lines, dotted, left frame,
# sparse, few icons, concise, transient_prompt, instant_prompt=verbose.
#
# Refactored into modular structure for easier maintenance.
# See: active/   - executed configuration files
#      reference/ - documentation and examples
#
# Type `p10k configure` to generate a new config.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

# Capture script directory before entering anonymous function
'builtin' 'local' '_p10k_dir'="${${(%):-%x}:A:h}"

() {
  emulate -L zsh -o extended_glob

  # Source all active configuration modules in order
  for f in "$_p10k_dir"/active/*.zsh(N); do
    source "$f"
  done
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
